# -*- coding: utf-8 -*-
"""Ninth_DSBDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NUpnI3uG9fwIAZ2NwuxJoIHcqZRR1P6Z
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r'/content/titanic_train.csv')
df

cols = df.columns
cols

df.info()

df.describe()

df.isnull().sum()

sns.boxplot(df['Sex'], df['Age'])

sns.boxplot(df['Sex'], df['Age'], df['Survived'])

