# -*- coding: utf-8 -*-
"""Tenth_DSBDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeQZFinaZ0BT4MGCqSTrEJRYlWo1VS9Y
"""

import numpy as np
import pandas as pd
df = pd.read_csv(r'/content/iris.csv', names=['col1','col2','col3','col4','col5'])

df.head()

column = len(list(df))
column

df.info()

np.unique(df['col5'])

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

fig, axes = plt.subplots(2, 2, figsize=(16, 8))
axes[0, 0].set_title("Distribution of first column")
axes[0, 0].hist(df["col1"])

axes[0, 1].set_title("Distribution of second column")
axes[0, 1].hist(df["col2"])

axes[1, 0].set_title("Distribution of third column")
axes[1, 0].hist(df["col3"])

axes[1, 1].set_title("Distribution of fourth column")
axes[1, 1].hist(df["col4"])

data_to_plot = [df['col1'], df['col2'], df['col3'], df['col4']]
sns.set_style("whitegrid")
fig = plt.figure(1, figsize=(12, 8))
ax = fig.add_subplot(111)
bp = ax.boxplot(data_to_plot)

df.describe()

