# -*- coding: utf-8 -*-
"""Third_DSBDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZcQGU3sttdvtoVECgwelw0Om6phHUtB
"""

import pandas as pd

df = pd.read_csv("/content/income.csv")
df.head()

df.age_group.unique()

# count number of non null income value in each age group
df.groupby(df.age_group).count()

# minimum value of income in each age group 
df.groupby(df.age_group).min()

# maximum value of income in each age group
df.groupby(df.age_group).max()

# mean of income in each age group
df.groupby(df.age_group).mean()

# standard deviation of income in each age group
df.groupby(df.age_group).std()

# describe gives count, mean, standard deviation, min, max, 25th percentile, 50th percentile and 75th percentile.
df.groupby(df.age_group).describe()

# Part 2
# Load iris data set
from sklearn import datasets
data = datasets.load_iris()
df = pd.DataFrame(data.data,columns=data.feature_names)
df['species'] = pd.Series(data.target)
df.head()

df.species.unique()

df.groupby(df.species)

# use aggregation function like count() to get all quantitive variables
df.groupby(df.species).count()

# max value of each quantitative variable according to categorical variable(species)
df.groupby(df.species).max()

# min value of each quantitative variable according to categorical variable(species)
df.groupby(df.species).min()

# mean of each quantitative variable according to categorical variable(species)
df.groupby(df.species).mean()

# standard deviation of each quantitative variable according to categorical variable(species)
df.groupby(df.species).std()

# for each categorical variable we get different summary statistics of sepal length column.
df.groupby(df.species)["sepal length (cm)"].describe()

df.groupby(df.species)["sepal width (cm)"].describe()

df.groupby(df.species)["petal length (cm)"].describe()

df.groupby(df.species)["petal width (cm)"].describe()

